### PR TITLE
#6 Prevent test files changes

### PR DESCRIPTION
**Pull request by vityaman**

### CODE REVIEW

**Comment by e1turin** [comment]
You can see an example of using such GHA in this PR: https://github.com/secs-dev/xv6-riscv/pull/20

**Comment by vityaman** [comment]
@e1turin, pofik. Anyway students should run these job in their repositories.

**Comment by vityaman** [comment]
@e1turin, GHA should be enabled by default. Don't forget to hit `Approve` button.

**Comment by e1turin** [comment]
@vityaman, I needed to enable this setting on the Actions tab after creating a fork, of course it's not the goal of this PR. I will approve right after you add other files used in tests.

**Comment by vityaman** [comment]
@e1turin, I added all files? Can you list them or do cherry-peek?

**Review by e1turin — APPROVED** [review]

**Pull request merged**
